services:
- type: pserv
  name: mysql
  plan: starter
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: DATABASE_NAME
    value: codepick_backend_production
  - key: MYSQL_USERNAME
    value: app_user
  - key: MYSQL_PASSWORD
    value: password
  - key: MYSQL_HOST
    value: true
